version: '3'
services:
  redis:
    image: redis:latest
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "users"
  user:
    depends_on:
      - redis
      - postgres
    build: .
    volumes:
      - "./env.yaml:/etc/user/config/env.yaml"
    ports:
      - 8888:8069
      - 8889:8079
