# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    container: golang:1.21-bookworm
    services:
      redis:
        image: redis:latest
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: "example"
          POSTGRES_DB: "users"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Test
      run: |
        export SETTING_PATH=$(pwd)/env.yaml.example
        go test -v ./...

  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/users:latest
  deploy:
    needs:
      - build
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: sudo systemctl restart users-docker.service
